services:
  - type: web
    name: mod-nak-samruat
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
    healthCheckPath: /healthz
